### ISSUE TITLE
LiftEquipmentRef within placeEquipments is not allowed

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#260] opened 2021-12-13 13:32 UTC
Reported in the accessibility meeting.

**Comment by skinkie** [comment] 2021-12-13 13:59
Might be related to https://github.com/NeTEx-CEN/NeTEx/issues/167

**Comment by Aurige** [comment] 2021-12-16 14:17
That right it is the same issue as [#167](https://github.com/NeTEx-CEN/NeTEx/issues/260#issuecomment-992505543)

**Comment by ue71603** [comment] 2022-01-04 14:05
Duplicate of #167

**Closed** 2022-01-04 14:05 UTC
Labels: bug
